services:
  app:
    image: cosmtrek/air # Официальный образ Air
    container_name: go-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "2345:2345"
    environment:
      - GOGC=10 # Опционально
    command: ["-c", ".air.toml"]
    stdin_open: true
    tty: true
